### ISSUE TITLE
用户信息增强

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#1]
# 增加头像
在数据库中能不能给用户增加一个用户头像URL的字段，在服务器开辟一个文件夹放头像
现在我前端的做法是使用了Gravatar头像，如果没有用户自定义头像的话，会根据用户邮箱来自动生成一个Gravatar。

在接口上补充一下用户URL的信息
- User.GetBaseInfo
- User.GetMultiBaseInfo

# 增加活动数量统计
- 发起过的活动数目
- 参加过的活动数目
- 飞机过的活动数目

**Comment by DiroKate** [comment]
还要增加一个接口

## 获取当前用户登录了的用户信息。
如果没有返回一个返回码给我。因为你的 GetUserInfo 只能获取指定的用户，而不是登录的用户

**Comment by later2015** [comment]
1. 用户URL、发起活动统计、参加活动统计、飞机活动统计的字段可以增加到用户基础信息表。
2. 获取当前登陆用户信息不需要新增接口啊。用户登陆成功的时候会返回用户ID，用返回的用户ID去查询当前登陆用户的信息就可以啦。

**Comment by later2015** [comment]
字段已加上 
"user_avatar_url":用户头像URL
,"user_start_event_count":发起活动次数统计,
"user_join_event_count":参加活动次数统计,
"user_fly_event_count":飞机活动次数统计
不过目前字段只是存在，数据还是不准的。后台逻辑还没加上去。
