### ISSUE TITLE
[新功能]用户修改报名资料的接口

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#13]
用户修改报名资料的接口没有；
用户删除BBS评论和活动评论的接口没有；

**Comment by later2015** [comment]
用户修改报名资料的接口已经增加:Event.editJoinEventInfo.
活动和BBS评论的编辑接口已经有了，满足大部分需求了。删除功能暂时不开放吧，最讨厌发了消息又撤回的了。（真要删除，他可以编辑内容为空，但至少其他人还知道他曾经回复过）
