### ISSUE TITLE
活动功能健全

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#2]
### 1. 增加新建活动和修改活动的接口
目前接口列表中没有这两个功能。

### 2.活动内容增加字段：
1. 出发地
1. 目的地
1. 集中点
1. 集中时间

**Comment by later2015** [comment]
可以有。

**Comment by later2015** [comment]
新建活动和修改活动接口已增加。
四个字段已加上。（脚本见db script目录）
