### ISSUE TITLE
[Features]增加BBS的分类过滤功能

### ISSUE THREAD

**Issue by DiroKate** [later2015/sysuhiker#8]
BBS.GetBBSList接口增加分类功能

![image](https://user-images.githubusercontent.com/3896617/28245819-807b2db0-6a41-11e7-9302-748692a791a9.png)

**Comment by DiroKate** [comment]
后台那里多加一个参数，让请求可以带type字段，按需返回。

**Comment by later2015** [comment]
已增加 postType 过滤参数。

**Comment by DiroKate** [comment]
@later2015 分类时候，total参数请返回分类后的总数，而不是全部总数。【bug】
